app1/urls.py
from django.urls import path
from . import views

app_name = "app1"#앱이름

urlpatterns = [
    #app1/ 기본 
    path('', views.index, name='index'),
    path('<int:pk>/',views.detail, name='detail'),
    path('search/',views.search, name='search' ),#검색
]

techblog/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('app1/', include('app1.urls')),#분리
]

app1/models.py
from ssl import create_default_context
from turtle import title
from django.db import models

# Create your models here.

class App1(models.Model):
    title=models.CharField(max_length=20)
    content=models.TextField()
    created_at=models.DateTimeField(auto_now_add=True)
    updated_at=models.DateTimeField(auto_now=True)
    hits=models.PositiveIntegerField(default = 0)#조회 수 

app1/views.py
from django.shortcuts import render
from.models import App1
from django.db.models import Q
# Create your views here.

def index(request):#목록
    index_contents = App1.objects.all().order_by('-pk')#최신순
    context={
        'index_contents':index_contents
    }
    return render(request, 'app1/index.html', context)

def detail(request, pk):#조회
    detail_contents = App1.objects.get(pk=pk)
    context={
        'detail_contents':detail_contents
    }
    response = render(request, 'app1/detail.html', context)
    detail_contents.hits +=1
    detail_contents.save()
    return response
def search(request):#검색 
    search= App1.objects.all().order_by('-pk')
    q = request.POST.get('q')
    if q:
        search = search.filter(Q(title__icontains=q)|Q(content__icontains=q))
        
        return render(request, 'app1/search.html',{'search':search, 'q':q})
    else:
        return render(request, 'app1/search.html')

app1/templates/app1/detail.html
{% extends 'base.html' %}
{% load filter %}
{% load django_bootstrap5 %}

{% block body %}
  <div class="m-5">
    <div class="d-flex justify-content-between">
      <h1>{{ detail_contents.title }}</h1>
      <div class="d-flex">
        <p>조회수:{{ detail_contents.hits }}</p>|
        <p>{{ detail_contents.created_at }}</p>
      </div>
    </div>
    <hr>

    <p>{{ detail_contents.content|mark }}</p>
  </div>
{% endblock %}

app1/templates/app1/index.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}
{% load filter %}
{% block body %}
<div class="d-flex">
  <div style="width:10ex;">
    <nav class="nav flex-column position-fixed">{% comment %} 상단고정? {% endcomment %}
      <li class="nav-item">
        <a class="nav-link text-dark" aria-current="page" href="{% url 'app1:index' %}">메인</a> {% comment %} index경로  {% endcomment %}
      </li>
      <li class="nav-item">
        <a class="nav-link text-dark" href="https://github.com/ANDONGWOO/TIL">깃허브</a>
      </li>
      <li class="nav-item">
        <a class="nav-link text-dark" href="http://yeoldybean-env.eba-ghf297im.ap-northeast-2.elasticbeanstalk.com/">프로젝트2</a>
      </li>
      <li class="nav-item">
        <a class="nav-link text-dark" href="http://ntkbean-env.eba-qinu3xmh.ap-northeast-2.elasticbeanstalk.com/">프로젝트3</a>
      </li>
    </nav>
  </div>
  <div class="container m-5">
  {% for index_content in index_contents %}
  <div class="card-body">
    <p class="card-text">{{ index_content.created_at }}</p>
    <a class="card-header fw-bold" href="{% url 'app1:detail' index_content.pk %}" style="text-decoration: none;"><h2>{{ index_content.title }}</h2></a>
    <p class="card-text">{{ index_content.content|mark }}</p>
  </div>
  <hr>
  {% endfor %}
    <div class="m-5 d-flex justify-content-center">
      <nav aria-label="Page navigation example ">
        <ul class="pagination">{% comment %} #페이지 10 {% endcomment %}
          <li class="page-item"><a class="page-link" href="#">이전</a></li>
          <li class="page-item"><a class="page-link" href="#">1</a></li>
          <li class="page-item"><a class="page-link" href="#">다음</a></li>
        </ul>
      </nav>
    </div>
  </div>
</div>
{% endblock %}

app1/templates/app1/search.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}
{% block body %}
  <div class="m-5">
    {% if not search %}
      <h1 class="">검색 없음</h1>
    {% else %}
      {% for i in search.all %}
        <a class="" href="{% url 'app1:detail' i.pk %}">{{ i.title }}</a>
        <hr>
      {% endfor %}
    {% endif %}
  </div>
{% endblock %}

techblog/templates/base.html
{% load django_bootstrap5 %} {% comment %} html에 개별 적용 {% endcomment %}

<!DOCTYPE html>
<html lang="en">

  <head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    {% bootstrap_css %}
    {% block css %}{% endblock css %} 
  </head>

  <body>
      <nav class="navbar navbar-light bg-dark sticky-top">
        <div class="container-fluid d-flex">
          <a class="navbar-brand text-white" href="{% url 'app1:index' %}">기술블로그</a>
          <form class="d-flex" role="search" action="{% url 'app1:search' %}" method="POST">
            {% csrf_token %}
            <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search" name="q" value="{{ q }}">
            <button class="btn btn-outline-dark text-white" type="submit">Search</button>
          </form>
        </div>
      </nav>
      <div class="container m-3">
      {% block body %}
      

      {% endblock body %}
      </div>
      {% bootstrap_javascript %}
  </body>
</html>